import { fail, ok } from "@/lib/http";
import { guardItAdminError, requireItSupport } from "@/lib/it-admin-guard";
import { mapWithConcurrency } from "@/lib/async-batch";
import { POS_GUARDS } from "@/lib/pos-resilience";
import { readThroughRuntimeCache } from "@/lib/route-runtime-cache";

function schemaMissing(message:string){const m=message.toLowerCase();return m.includes("does not exist")||m.includes("undefined column")||m.includes("pgrst")}
function parseMinutes(sp:URLSearchParams){const n=Number(sp.get("minutes")??POS_GUARDS.deadLetterWindowMinutes);return Number.isFinite(n)?Math.max(5,Math.min(1440,Math.trunc(n))):POS_GUARDS.deadLetterWindowMinutes}
function statusCode(v:unknown){const n=Number(v);return Number.isFinite(n)&&n>=100&&n<=599?Math.trunc(n):null}
function routeName(v:unknown){return typeof v==="string"&&v.startsWith("/")?v.slice(0,160):"unknown"}
export async function GET(req:Request){const started=Date.now();try{
 const {supabase,auth}=await requireItSupport(); const {searchParams}=new URL(req.url); const minutes=parseMinutes(searchParams); const requested=String(searchParams.get("branch_id")??"").trim()||null;
 const cacheKey=`platform-pos-monitor:${auth.userId}:${minutes}:${requested??"all"}`;
 const {value:payload,source}=await readThroughRuntimeCache({key:cacheKey,ttlMs:5000,loader:async()=>{
  const staleSince=new Date(Date.now()-POS_GUARDS.staleQueuedMinutes*60000).toISOString(); const windowSince=new Date(Date.now()-minutes*60000).toISOString();
  let branchQuery=supabase.from("branches").select("id,name,tenant_id").eq("is_active",true).order("name").limit(250); if(requested) branchQuery=branchQuery.eq("id",requested);
  const {data:branches,error:branchError}=await branchQuery; if(branchError)throw new Error(`branches_query_failed:${branchError.message}`);
  const tenantIds=[...new Set((branches??[]).map(r=>String(r.tenant_id)).filter(Boolean))]; const {data:tenants,error:tenantError}=tenantIds.length?await supabase.from("tenants").select("id,code,name").in("id",tenantIds):{data:[],error:null}; if(tenantError)throw new Error(`tenants_query_failed:${tenantError.message}`);
  const tenantMap=new Map((tenants??[]).map(t=>[String(t.id),{code:String(t.code??""),name:String(t.name??"")} ]));
  const safeCount=async(q:PromiseLike<{count:number|null;error:{message:string}|null}>)=>{const r=await q;if(r.error){if(schemaMissing(r.error.message))return 0;throw new Error(r.error.message)}return r.count??0};
  const items=await mapWithConcurrency({items:branches??[],concurrency:4,worker:async(branch)=>{const branchId=String(branch.id),tenantId=String(branch.tenant_id);const perf=async()=>{const {data,error}=await supabase.from("audit_logs").select("metadata").eq("tenant_id",tenantId).eq("branch_id",branchId).eq("action","pos_route_perf").gt("created_at",windowSince).order("created_at",{ascending:false}).limit(500);if(error){if(schemaMissing(error.message))return{total:0,c4xx:0,c409:0,c5xx:0,topRoutes:[] as Array<{route:string;count:number}>};throw new Error(error.message)}let total=0,c4xx=0,c409=0,c5xx=0;const rm=new Map<string,number>();for(const row of data??[]){const md=(row as {metadata?:Record<string,unknown>|null}).metadata??{};const s=statusCode(md.status_code);if(!s||s<400)continue;total++;if(s>=500)c5xx++;else c4xx++;if(s===409)c409++;const rn=routeName(md.route);rm.set(rn,(rm.get(rn)??0)+1)}return{total,c4xx,c409,c5xx,topRoutes:[...rm.entries()].map(([route,count])=>({route,count})).sort((a,b)=>b.count-a.count).slice(0,3)}};
   const [queued,stale,printQueue,printFailed,dead,orderDead,paymentDead,p]=await Promise.all([
    safeCount(supabase.from("orders").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).eq("status","queued")),safeCount(supabase.from("orders").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).eq("status","queued").lt("created_at",staleSince)),safeCount(supabase.from("print_jobs").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).in("status",["pending","printing","retrying"])),safeCount(supabase.from("print_jobs").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).eq("status","failed").gt("created_at",windowSince)),safeCount(supabase.from("audit_logs").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).in("action",["pos_order_dead_letter","pos_payment_dead_letter","pos_print_dead_letter"]).gt("created_at",windowSince)),safeCount(supabase.from("audit_logs").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).eq("action","pos_order_dead_letter").gt("created_at",windowSince)),safeCount(supabase.from("audit_logs").select("id",{count:"exact",head:true}).eq("tenant_id",tenantId).eq("branch_id",branchId).eq("action","pos_payment_dead_letter").gt("created_at",windowSince)),perf()]);
   let level:"ok"|"warn"|"critical"="ok";if(queued>=POS_GUARDS.orderQueueHardLimit||printQueue>=POS_GUARDS.printQueueHardLimit||p.c5xx>=3)level="critical";else if(stale>0||dead>0||printFailed>0||p.total>0)level="warn";const tenant=tenantMap.get(tenantId);
   return{branch_id:branchId,branch_name:`${tenant?.code||"STORE"} · ${String(branch.name??branchId)}`,level,queued_orders:queued,queued_orders_stale:stale,print_queue_depth:printQueue,print_failed_recent:printFailed,dead_letters_recent:dead,order_dead_letters_recent:orderDead,payment_dead_letters_recent:paymentDead,api_errors_recent_total:p.total,api_errors_4xx_recent:p.c4xx,api_errors_409_recent:p.c409,api_errors_5xx_recent:p.c5xx,api_error_routes_top:p.topRoutes};}});
  const totals=items.reduce((a,r)=>{a.queued_orders+=r.queued_orders;a.dead_letters_recent+=r.dead_letters_recent+r.print_failed_recent;a.order_dead_letters_recent+=r.order_dead_letters_recent;a.payment_dead_letters_recent+=r.payment_dead_letters_recent;a.api_errors_recent_total+=r.api_errors_recent_total;a.api_errors_4xx_recent+=r.api_errors_4xx_recent;a.api_errors_409_recent+=r.api_errors_409_recent;a.api_errors_5xx_recent+=r.api_errors_5xx_recent;if(r.level==="critical")a.critical++;if(r.level==="warn")a.warn++;return a},{branches:items.length,queued_orders:0,dead_letters_recent:0,order_dead_letters_recent:0,payment_dead_letters_recent:0,critical:0,warn:0,api_errors_recent_total:0,api_errors_4xx_recent:0,api_errors_409_recent:0,api_errors_5xx_recent:0});
  return{generated_at:new Date().toISOString(),filters:{minutes,branch_id:requested},limits:{order_queue_limit:POS_GUARDS.orderQueueHardLimit,print_queue_limit:POS_GUARDS.printQueueHardLimit},totals,items};}});
 const response=ok(payload);response.headers.set("cache-control","no-store");response.headers.set("x-admin-pos-monitor-cache",source);response.headers.set("x-admin-pos-monitor-ms",String(Date.now()-started));return response;
 }catch(error){const message=error instanceof Error?error.message:"Unknown error";if(message.startsWith("branches_query_failed:")||message.startsWith("tenants_query_failed:")){const response=fail("monitor_query_failed",message,500);response.headers.set("x-admin-pos-monitor-ms",String(Date.now()-started));return response}const response=guardItAdminError(error);response.headers.set("x-admin-pos-monitor-ms",String(Date.now()-started));return response}}
