<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Cpipos.WindowsRuntime</AssemblyName>
    <RootNamespace>Cpipos.WindowsRuntime</RootNamespace>
    <Version>0.1.1</Version>
    <FileVersion>0.1.1.0</FileVersion>
    <AssemblyVersion>0.1.1.0</AssemblyVersion>
    <ApplicationIcon></ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
  </ItemGroup>
</Project>
