<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>Cpipos.WindowsRuntime</AssemblyName>
    <RootNamespace>Cpipos.WindowsRuntime</RootNamespace>
    <Version>0.1.4</Version>
    <FileVersion>0.1.4.0</FileVersion>
    <AssemblyVersion>0.1.4.0</AssemblyVersion>
    <ApplicationIcon>assets\cpipos.ico</ApplicationIcon>
    <Win32Resource></Win32Resource>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="assets\cpipos.ico" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
  </ItemGroup>
</Project>
