import { getPosApiAuthContext } from "@/lib/pos-api-auth";
import { featureGateFail, requirePosApiFeature } from "@/lib/pos-api-feature-guard";
import { fail, ok } from "@/lib/http";

const GEO_URL="https://raw.githubusercontent.com/thailand-geography-data/thailand-geography-json/main/src/geography.json";
type GeoRow={provinceNameTh?:string;districtNameTh?:string;subdistrictNameTh?:string;postalCode?:number|string};
let cachedRows:GeoRow[]|null=null; let loading:Promise<GeoRow[]>|null=null;
async function requireScope(){const auth=await getPosApiAuthContext({requireBranchScope:true,requiredPermission:"receipts:view"});await requirePosApiFeature(auth,"core_pos_sales");return auth;}
async function loadRows(){if(cachedRows)return cachedRows;if(!loading){loading=fetch(GEO_URL,{headers:{Accept:"application/json"}}).then(async(response)=>{if(!response.ok)throw new Error(`Thailand address dataset unavailable (${response.status})`);const body=(await response.json()) as unknown;if(!Array.isArray(body))throw new Error("Thailand address dataset format is invalid.");cachedRows=body as GeoRow[];return cachedRows;}).finally(()=>{loading=null;});}return loading;}
export async function GET(request:Request){try{await requireScope();const postcode=String(new URL(request.url).searchParams.get("postcode")??"").replace(/\D/g,"").slice(0,5);if(!/^\d{5}$/.test(postcode))return fail("invalid_postcode","รหัสไปรษณีย์ต้องมี 5 หลัก",422);const rows=await loadRows();const unique=new Map<string,{subdistrict:string;district:string;province:string;postal_code:string}>();for(const row of rows){if(String(row.postalCode??"")!==postcode)continue;const subdistrict=String(row.subdistrictNameTh??"").trim();const district=String(row.districtNameTh??"").trim();const province=String(row.provinceNameTh??"").trim();if(!subdistrict||!district||!province)continue;const key=`${province}|${district}|${subdistrict}`;unique.set(key,{subdistrict,district,province,postal_code:postcode});}const options=Array.from(unique.values()).sort((a,b)=>`${a.province}${a.district}${a.subdistrict}`.localeCompare(`${b.province}${b.district}${b.subdistrict}`,"th"));return ok({postcode,options});}catch(error){const featureError=featureGateFail(error);if(featureError)return featureError;return fail("postcode_lookup_failed",error instanceof Error?error.message:"Postcode lookup failed.",500);}}
