import { getPosApiAuthContext } from "@/lib/pos-api-auth";
import { featureGateFail, requirePosApiFeature } from "@/lib/pos-api-feature-guard";
import { fail, ok } from "@/lib/http";
import { loadReceiptStoreProfile } from "@/lib/services/store-profile-service";
import { getSupabaseServiceClient } from "@/lib/supabase-admin";

type IssuePayload={recipient_id?:string;order_id?:string;paper_width_mm?:number|string};
type RecipientRow={id:string;entity_type:string;display_name:string;tax_id:string;address_line:string;subdistrict:string;district:string;province:string;postal_code:string};
type OrderRow={id:string;order_no:string;status:string;subtotal:number|null;discount_amount:number|null;grand_total:number|null;total_amount:number|null;tax_total:number|null;created_at:string;payment_completed_at:string|null;metadata:unknown};
type TaxLine={label:string;rate_pct:number;mode:string;amount:number};
function round(value:number){return Number((Number.isFinite(value)?value:0).toFixed(2));}
function metadataArray(metadata:unknown,key:string):unknown[]{if(!metadata||typeof metadata!=="object"||Array.isArray(metadata))return[];const value=(metadata as Record<string,unknown>)[key];return Array.isArray(value)?value:[];}
function parseTaxLines(metadata:unknown):TaxLine[]{return metadataArray(metadata,"tax_lines").map((raw)=>{const row=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};return{label:String(row.label??""),rate_pct:Number(row.rate_pct??0),mode:String(row.mode??""),amount:round(Number(row.amount??0))};}).filter((row)=>row.label||row.amount!==0);}
function isVatLabel(label:string){const value=label.toLowerCase().replace(/\s/g,"");return value.includes("vat")||value.includes("ภาษีมูลค่าเพิ่ม")||value.includes("มูลค่าเพิ่ม");}
function jsonRecord(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};}
async function requireScope(){const auth=await getPosApiAuthContext({requireBranchScope:true,requiredPermission:"receipts:view"});await requirePosApiFeature(auth,"core_pos_sales");return auth;}
async function loadExisting(tenantId:string,branchId:string,orderId:string){return getSupabaseServiceClient().from("pos_tax_invoices").select("*").eq("tenant_id",tenantId).eq("branch_id",branchId).eq("order_id",orderId).maybeSingle();}

export async function POST(request:Request){try{const auth=await requireScope();const payload=(await request.json().catch(()=>null)) as IssuePayload|null;const recipientId=String(payload?.recipient_id??"").trim();const orderId=String(payload?.order_id??"").trim();const paperWidth=Number(payload?.paper_width_mm)===58?58:80;if(!recipientId||!orderId)return fail("tax_invoice_input_required","กรุณาเลือกผู้รับใบกำกับภาษีและบิล",422);const supabase=getSupabaseServiceClient();
const existing=await loadExisting(auth.tenantId!,auth.branchId!,orderId);if(existing.error)return fail("tax_invoice_query_failed",existing.error.message,500);if(existing.data)return ok({invoice:existing.data,reused:true});
const recipient=await supabase.from("pos_tax_recipients").select("id,entity_type,display_name,tax_id,address_line,subdistrict,district,province,postal_code").eq("tenant_id",auth.tenantId!).eq("branch_id",auth.branchId!).eq("id",recipientId).eq("is_active",true).maybeSingle<RecipientRow>();if(recipient.error)return fail("tax_recipient_query_failed",recipient.error.message,500);if(!recipient.data)return fail("tax_recipient_not_found","ไม่พบข้อมูลผู้เสียภาษี",404);
const order=await supabase.from("orders").select("id,order_no,status,subtotal,discount_amount,grand_total,total_amount,tax_total,created_at,payment_completed_at,metadata").eq("tenant_id",auth.tenantId!).eq("branch_id",auth.branchId!).eq("id",orderId).maybeSingle<OrderRow>();if(order.error)return fail("tax_invoice_order_query_failed",order.error.message,500);if(!order.data||order.data.status!=="completed")return fail("tax_invoice_order_not_completed","ออกใบกำกับภาษีได้เฉพาะบิลที่ชำระเงินเสร็จแล้ว",422);
const [items,payments,branch,storeProfile,taxSettings]=await Promise.all([
supabase.from("order_items").select("product_id,name,quantity,unit_price,line_total,notes").eq("tenant_id",auth.tenantId!).eq("branch_id",auth.branchId!).eq("order_id",orderId),
supabase.from("payments").select("method,amount,status,created_at").eq("tenant_id",auth.tenantId!).eq("branch_id",auth.branchId!).eq("order_id",orderId),
supabase.from("branches").select("id,name,code").eq("id",auth.branchId!).eq("tenant_id",auth.tenantId!).maybeSingle(),loadReceiptStoreProfile(auth.tenantId!),
supabase.from("tenant_tax_settings").select("settings,branch_id").eq("tenant_id",auth.tenantId!).order("branch_id",{ascending:false})]);
if(items.error)return fail("tax_invoice_items_query_failed",items.error.message,500);if(payments.error)return fail("tax_invoice_payments_query_failed",payments.error.message,500);if(branch.error)return fail("tax_invoice_branch_query_failed",branch.error.message,500);
const taxLines=parseTaxLines(order.data.metadata);const vatLine=taxLines.find((line)=>isVatLabel(line.label))??(taxLines.length===1?taxLines[0]:null);const vatAmount=round(vatLine?.amount??0);const vatRate=round(vatLine?.rate_pct??0);const total=round(Number(order.data.grand_total??order.data.total_amount??0));const netFallback=round(Math.max(0,Number(order.data.subtotal??0)-Number(order.data.discount_amount??0)));const subtotalBeforeVat=vatLine?.mode==="add_to_bill"?round(Math.max(0,total-vatAmount)):netFallback||round(Math.max(0,total-vatAmount));
const settingsRows=(taxSettings.data??[]) as Array<{settings:unknown;branch_id:string|null}>;const branchSettings=settingsRows.find((row)=>row.branch_id===auth.branchId)?.settings??settingsRows.find((row)=>row.branch_id==null)?.settings;const sellerSettings=jsonRecord(branchSettings);const sellerTaxId=String(sellerSettings.tax_id??sellerSettings.seller_tax_id??sellerSettings.company_tax_id??"").replace(/\D/g,"");
const recipientSnapshot={...recipient.data};const receiptSnapshot={order_id:order.data.id,order_no:order.data.order_no,created_at:order.data.created_at,paid_at:order.data.payment_completed_at,subtotal:Number(order.data.subtotal??0),discount_amount:Number(order.data.discount_amount??0),tax_total:Number(order.data.tax_total??0),tax_lines:taxLines,total_amount:total,items:items.data??[],payments:payments.data??[],branch:{id:auth.branchId,name:String(branch.data?.name??""),code:String(branch.data?.code??"")},seller:{code:storeProfile?.code??"",name:storeProfile?.display_name||storeProfile?.name||"",address:storeProfile?.company_address??"",phone:storeProfile?.contact_phone??"",tax_id:sellerTaxId}};
const safeOrderNo=String(order.data.order_no||order.data.id).replace(/[^0-9A-Za-zก-๙_-]/g,"").slice(0,48);const invoiceNo=`TAX-${safeOrderNo}`;
let inserted=await supabase.from("pos_tax_invoices").insert({tenant_id:auth.tenantId!,branch_id:auth.branchId!,recipient_id:recipientId,order_id:orderId,invoice_no:invoiceNo,paper_width_mm:paperWidth,status:"issued",subtotal_before_vat:subtotalBeforeVat,vat_rate_pct:vatRate,vat_amount:vatAmount,total_amount:total,recipient_snapshot:recipientSnapshot,receipt_snapshot:receiptSnapshot,issued_by:auth.userId}).select("*").single();
if(inserted.error){if(inserted.error.code==="23505"){const raced=await loadExisting(auth.tenantId!,auth.branchId!,orderId);if(!raced.error&&raced.data)return ok({invoice:raced.data,reused:true});}return fail("tax_invoice_create_failed",inserted.error.message,500);}return ok({invoice:inserted.data,reused:false});
}catch(error){const featureError=featureGateFail(error);if(featureError)return featureError;return fail("tax_invoice_issue_failed",error instanceof Error?error.message:"Failed to issue tax invoice.",500);}}
